/* Students */
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (1, null, "ATIVO", "Amanda",  "10977591999", "186908714", "amanda@email.com", TRUE, "Feminino", "Solteiro", "Rua da Amanda", "Bairro da Amanda", "Cidade da Amanda", "PR", "Local de referência da Amanda", null, "2000-04-23 00:00:00", "2020-01-26 00:00:00", "Felype", "2020-02-14 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (2, null, "ATIVO", "Bruno",  "38045798920", "211474083", null, FALSE, "Masculino", "Casado", "Rua da Bruno", "Bairro da Bruno", "Cidade da Bruno", "PR", "Local de referência da Bruno", null, "2000-01-01 00:00:00", "2020-02-29 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (3, null, "AGUARDANDO", "Camila",  "62866153936", "107766668", "Camila@email.com", TRUE, "Feminino", "Solteiro", "Rua da Camila", "Bairro da Camila", "Cidade da Camila", "PR", "Local de referência da Camila", null, null, "2020-02-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (4, null, "AGUARDANDO", "Diogo",  "35330440920", "190258731", "Diogo@email.com", FALSE, "Masculino", "Solteiro", "Rua da Diogo", "Bairro da Diogo", "Cidade da Diogo", "PR", "Local de referência da Diogo", null, "1997-03-01 00:00:00", "2020-03-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (5, null, "ATIVO", "Eduardo",  "56986676913", "392716999", "Eduardo@email.com", TRUE, "Masculino", "Solteiro", "Rua da Eduardo", "Bairro da Eduardo", "Cidade da Eduardo", "PR", "Local de referência da Eduardo", null, "1999-01-05 00:00:00", "2020-04-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (6, null, "INATIVO", "Fernanda",  "56986676913", "221260729", "Fernanda@email.com", TRUE, "Feminino", "Solteiro", "Rua da Fernanda", "Bairro da Fernanda", "Cidade da Fernanda", "PR", "Local de referência da Fernanda", null, "2001-08-23 00:00:00", "2020-05-26 00:00:00", "Felype", "2020-06-01 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (7, null, "ATIVO", "Gabriel",  "56986676913", "358658433", "Gabriel@email.com", FALSE, "Masculino", "Solteiro", "Rua da Gabriel", "Bairro da Gabriel", "Cidade da Gabriel", "PR", null, "ObservaÃ§ão do Gabriel", "2002-04-01 00:00:00", "2020-06-26 00:00:00", "Felype", "2020-07-17 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (8, null, "ATIVO", "João",  "53138947905", "183572026", null, FALSE, "Masculino", "Solteiro", "Rua da João", "Bairro da João", "Cidade da João", "PR", "Local de referência da João", null, "1992-06-018 00:00:00", "2020-08-26 00:00:00", "Felype", "2020-09-01 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (9, null, "AGUARDANDO", "Leandro",  "82612125990", "315397809", "Leandro@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Leandro", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Teste",  "82612125990", "315397809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Amanda Pereira",  "82612125990", "315397809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);
insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Amanda3 com Outro Sobrenome",  "82612125990", "315397809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);
insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Bruno da Silva",  "82612125990", "315397809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (1, "Lugar Nenhum", "Felype", "Lapa", "223423", "paula@gmail.com", "Rua Carlos Antonio", "Paula de Fatima Souza e Filha", "424", "F", "PR", true);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (2, "Los Verejos", "Felype", "Whashinton", "23423", "caska@gmail.com", "Rua Novo Pedro", "Caska das árvores maiores", "5345", "F", "PR", true);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (3, "Aldeia da Folha", "Felype", "Sï¿½o Paulo", "53453", "camile@gmail.com", "Rua Carlos Pereiras", "Chritian de Oliveira Pereiras", "242", "M", "PR", false);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (4, "Vila Nova Fibrurgo", "Felype", "Petrolina", "444444444", "camile@gmail.com", "Rua Bermudas", "Triangulo das Bermudas", "34234", "M", "PR", true);
 
insert into contato(id, descricao, numero, contact_id_student) values(1,"NÃºmero do aluno","(41) 98868-0206", 1);
insert into contato(id, descricao, numero, contact_id_student) values(2,"NÃºmero da mãe", "912345678", 2);
insert into contato(id, descricao, numero, contact_id_student) values(3, "--", "9123456781234567890", 2);
insert into contato(id, descricao, numero, contact_id_responsible) values(4,"Namorado", "988888877", 1);
insert into contato(id, descricao, numero, contact_id_responsible) values(5,"VÃ³", "123456791", 2);
 
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (1, 1,  "Mãe");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (3, 2, "Tia");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (1, 3, "Sobinho");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (2, 3, "Amigo");

insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (1, '2020-11-01 01:00:00', "uma nova anotaÃ§ão que será adicionada", "Felype", 1);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (2, '2020-10-01 02:00:00', "segunda anotaÃ§ão", "Felype", 3);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (3, '2020-09-01 03:00:00', "terceira anotaÃ§ão\n\n\ncom quebra de linhas", "Felype", 1);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (4, '2020-07-01 04:00:00', "quinta anotaÃ§ão", "Felype", 3);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (5, '2020-02-01 05:00:00', "sexta anotaÃ§ão", "Felype", 2);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (6, '2020-03-01 06:00:00', "sétima anotaÃ§ão com uma quantidade tremendamente um pouquinho maior do que as anotaÃ§Ãµes anteriores, sendo que essa também possui quebra de linhas.\n\n\n Quebras inseridas com barras e a letra n, vamos ver se irá funcionar ou não", "Felype", 2);
    
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(1, 'Ativa', '2020-09-01', "Feh", "Teste sem resp.", null, 1);
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(2, 'Cancelada', '2010-10-01', "Feh", "Teste sem resp.", 1, 1);
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(3, 'Ativa', '2020-11-01', "Feh", "Teste com resp.", 2, 3);
 
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(1,  '2020-09-01', '2020-09-01', 5, 3, 0, "Paga", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(2,  '2020-09-02', '2020-09-02', 5, 3, 1, "Paga", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(3,  '2020-09-03', '2020-09-05', 5, 3, 2, "Aberta", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(4,  '2020-09-04', null, 5, 3, 3, "Aberta", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(5,  '2020-09-05', null, 5, 3, 4, "Aberta", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(6,  '2020-09-06', null, 5, 3, 5, "Aberta", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(7,  '2020-09-07', null, 5, 3, 6, "Aberta", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(8,  '2020-09-08', null, 5, 3, 7, "Cancelada", 89.90, 1);
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(9,  '2020-09-07', null, 5, 3, 6, "Aberta", 89.90, 3);
 
insert into parcela(numero_documento, data_parcela, data_pagamento, desconto, dias_desconto, parcela_numero, situacao, valor, matricula_codigo) values(10,  '2020-09-08', null, 5, 3, 2, "Aberta", 200.90, 2);   
    
insert into colaborador (id, nome, sigla, email, cargo, numero_contato, usuario_login, senha_login) values (1, "Felype Aurélio Ganzert", "Felype", "felipe.ganzert", "professor", "41988680806", "feh", "feh@123");
insert into colaborador (id, nome, sigla, email, cargo, numero_contato, usuario_login, senha_login) values (2, "Paula Cristina", "Paula", "paula@email.com", "professor", "12345", "paula", "paula123");