/* Students */
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "ATIVO", "Amanda",  "10977591999", "1869584714", "amanda@email.com", TRUE, "Feminino", "Solteiro", "Rua da Amanda", "Bairro da Amanda", "Cidade da Amanda", "PR", "Local de referência da Amanda", null, "2000-04-23 00:00:00", "2020-01-26 00:00:00", "Felype", "2020-02-14 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "ATIVO", "Bruno",  "38045798954", "211176083", null, FALSE, "Masculino", "Casado", "Rua da Bruno", "Bairro da Bruno", "Cidade da Bruno", "PR", "Local de referência da Bruno", null, "2000-01-01 00:00:00", "2020-02-29 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "AGUARDANDO", "Camila",  "62867153936", "107765668", "Camila@email.com", TRUE, "Feminino", "Solteiro", "Rua da Camila", "Bairro da Camila", "Cidade da Camila", "PR", "Local de referência da Camila", null, null, "2020-02-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "AGUARDANDO", "Diogo",  "35334340920", "193578731", "Diogo@email.com", FALSE, "Masculino", "Solteiro", "Rua da Diogo", "Bairro da Diogo", "Cidade da Diogo", "PR", "Local de referência da Diogo", null, "1997-03-01 00:00:00", "2020-03-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "ATIVO", "Eduardo",  "56986678213", "392736999", "Eduardo@email.com", TRUE, "Masculino", "Solteiro", "Rua da Eduardo", "Bairro da Eduardo", "Cidade da Eduardo", "PR", "Local de referência da Eduardo", null, "1999-01-05 00:00:00", "2020-04-26 00:00:00", "Felype", null);
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "INATIVO", "Fernanda",  "56981476913", "296260729", "Fernanda@email.com", TRUE, "Feminino", "Solteiro", "Rua da Fernanda", "Bairro da Fernanda", "Cidade da Fernanda", "PR", "Local de referência da Fernanda", null, "2001-08-23 00:00:00", "2020-05-26 00:00:00", "Felype", "2020-06-01 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "ATIVO", "Gabriel",  "56986674813", "358658433", "Gabriel@email.com", FALSE, "Masculino", "Solteiro", "Rua da Gabriel", "Bairro da Gabriel", "Cidade da Gabriel", "PR", null, "ObservaÃ§ão do Gabriel", "2002-04-01 00:00:00", "2020-06-26 00:00:00", "Felype", "2020-07-17 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "ATIVO", "João",  "53138940605", "183572026", null, FALSE, "Masculino", "Solteiro", "Rua da João", "Bairro da João", "Cidade da João", "PR", "Local de referência da João", null, "1992-06-018 00:00:00", "2020-08-26 00:00:00", "Felype", "2020-09-01 00:00:00");
insert into aluno(id, ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, null, "AGUARDANDO", "Leandro",  "82692125890", "315397809", "Leandro@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Leandro", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Teste",  "82692125990", "315317809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Amanda Pereira",  "82613125590", "315396449", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);
insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Amanda3 com Outro Sobrenome",  "82612124990", "315397809", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);
insert into aluno(ra_antigo, situacao, nome,  cpf, rg, email, send_email, sexo, estado_civil,endereco, bairro, cidade, uf, local_referencia, observacao, data_nascimento, data_cadastro, cadastrado_por, data_ultima_edicao) values (null, "AGUARDANDO", "Bruno da Silva",  "82611125495", "315397509", "Teste@email.com", TRUE, "Masculino", "Divorciado", null, null, null, null, "Local de referência da Teste", null, "1970-05-23 00:00:00", "2020-09-26 00:00:00", "Felype", null);

insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (1, "Lugar Nenhum", "Felype", "Lapa", "36598642387", "paula@gmail.com", "Rua Carlos Antonio", "Paula de Fatima Souza e Filha", "424", "Feminino", "PR", true);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (2, "Los Verejos", "Felype", "Whashinton", "25479685212", "caska@gmail.com", "Rua Novo Pedro", "Caska das árvores maiores", "5345", "Feminino", "PR", true);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (3, "Aldeia da Folha", "Felype", "Sï¿½o Paulo", "36495875625", "camile@gmail.com", "Rua Carlos Pereiras", "Chritian de Oliveira Pereiras", "242", "Masculino", "PR", false);
insert into responsavel(id, bairro, cadastrado_por, cidade, cpf, email, endereco, nome, rg, sexo, uf, send_email) values (4, "Vila Nova Fibrurgo", "Felype", "Petrolina", "66633322215", "camile@gmail.com", "Rua Bermudas", "Triangulo das Bermudas", "34234", "Masculino", "PR", true);
 
insert into contato(id, descricao, numero, contact_id_student) values(1,"Número do aluno","41988680206", 1);
insert into contato(id, descricao, numero, contact_id_student) values(2,"Número da mãe", "912345678", 2);
insert into contato(id, descricao, numero, contact_id_student) values(3, "--", "978685025", 2);
insert into contato(id, descricao, numero, contact_id_responsible) values(4,"Namorado", "988888877", 1);
insert into contato(id, descricao, numero, contact_id_responsible) values(5,"Vó", "123456791", 2);
 
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (1, 1,  "Mãe");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (3, 2, "Tia");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (1, 3, "Sobinho");
insert into responsavel_aluno (aluno_id, responsavel_id, parentesco) values (2, 3, "Amigo");

insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (1, '2020-11-01 01:00:00', "uma nova anotação que será adicionada", "Felype", 1);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (2, '2020-10-01 02:00:00', "segunda anotação", "Felype", 3);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (3, '2020-09-01 03:00:00', "terceira anotação\n\n\ncom quebra de linhas", "Felype", 1);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (4, '2020-07-01 04:00:00', "quinta anotação", "Felype", 3);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (5, '2020-02-01 05:00:00', "sexta anotação", "Felype", 2);
insert into anotacoes (id, data, descricao, colaborador_responsavel, aluno_id) value (6, '2020-03-01 06:00:00', "sétima anotação com uma quantidade tremendamente um pouquinho maior do que as anotações anteriores, sendo que essa também possui quebra de linhas.\n\n\n Quebras inseridas com barras e a letra n, vamos ver se irá funcionar ou não", "Felype", 2);
    
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(1, 'ABERTA', '2020-09-01', "Feh", "Teste sem resp.", null, 1);
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(2, 'Cancelada', '2010-10-01', "Feh", "Teste sem resp.", 1, 1);
insert into matricula(code, situacao, data_matricula, matriculado_por, motivo, responsavel_financeiro_id, aluno_id) values(3, 'ABERTA', '2020-11-01', "Feh", "Teste com resp.", 2, 3);
 
 
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (1, '2019/01/10', '2019/01/15', 3, "DINHEIRO", 0, "Paula", "PAGA", 138.90, 5.00, 138.90, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (2, '2019/02/10', '2019/02/15', 3, "DINHEIRO", 1, "Paula", "PAGA", 138.90, 5.00, 138.90, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (3, '2019/03/10', '2019/03/15', 3, "DINHEIRO", 2, "Pedro", "PAGA", 138.90, 5.00, 138.90, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (4, '2019/04/10', '2019/04/15', 3, "DINHEIRO", 3, "Vitória", "PAGA", 138.90, 5.00, 138.90, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (5, '2019/05/10', '2019/05/15', 3, "DÉBITO", 4, "Paula", "PAGA", 138.90, 5.00, 138.90, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (6, '2019/06/10', null, 3, null, 5, null, "ABERTA", 138.90, 5.00, null, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (7, '2019/07/10', null, 3, null, 6, null, "ABERTA", 138.90, 5.00, null, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (8, '2020/11/10', null, 3, null, 7, null, "ABERTA", 138.90, 5.00, null, 1);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (9, '2020/12/10', null, 3, null, 8, null, "ABERTA", 138.90, 5.00, null, 1); 
 
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (10, '2019/01/10', '2019/01/15', 3, "DINHEIRO", 0, "Paula", "PAGA", 238.90, 50.00, 238.90, 3);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (11, '2019/02/10', '2019/02/15', 3, "DINHEIRO", 1, "Henrique", "PAGA", 238.90, 50.00, 288.90, 3);

INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (12, '2019/01/10', '2019/01/15', 3, "DINHEIRO", 0, "Paula", "PAGA", 258.90, 10.00, 258.90, 2);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (13, '2019/02/10', '2019/02/15', 3, "DINHEIRO", 1, "Ana", "PAGA", 258.90, 10.00, 258.90, 2); 
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (14, '2019/03/10', null, 3, null, 2, null, "CANCELADA", 258.90, 10.00, null, 2);
 INSERT INTO parcela(numero_documento, data_parcela, data_pagamento, dias_multa_atraso, pago_com, parcela_numero, pagamento_recebido_por, situacao, valor, valor_multa_atraso, valor_pago, matricula_codigo) VALUES (15, '2019/04/10', null, 3, null, 3, null, "CANCELADA", 258.90, 10.00, null, 2);
 
  
insert into colaborador (id, nome, sigla, email, cargo, numero_contato, usuario_login, senha_login) values (1, "Felype Aurélio Ganzert", "Felype", "felipe.ganzert", "professor", "41988680806", "feh", "feh@123");
insert into colaborador (id, nome, sigla, email, cargo, numero_contato, usuario_login, senha_login) values (2, "Paula Cristina", "Paula", "paula@email.com", "professor", "12345", "paula", "paula123");